#ifndef _ROUTING_HPP_
#define _ROUTING_HPP_

#include "types.hpp"
#include "bgl_graph_info.hpp"

typedef std::vector<std::vector<double> > Routes;
typedef std::vector<vertex_descriptor> node_hop;
typedef std::vector<std::vector<vertex_descriptor> >next_hop;

next_hop build_forwarding_tables(Graph G, int route, Routes *R);
next_hop ospf(Graph G, Routes *R);

/* This code is from: 
 * http://www.boost.org/doc/libs/1_42_0/libs/graph/example/dave.cpp
 * It is used to ensure that I can also use dijkstra's visitor algorithm
 * to generate a predecessor map for routing.
 */
template <class NewGraph, class Tag>
struct graph_copier : public boost::base_visitor<graph_copier<NewGraph, Tag> >{
  typedef Tag event_filter;
  graph_copier(NewGraph& graph) : new_g(graph) { }
  template <class Edge, class Graph>
  void operator()(Edge e, Graph& g) {
    add_edge(source(e, g), target(e, g), new_g);
  }
  private:
  NewGraph& new_g;
};
template <class NewGraph, class Tag>
inline graph_copier<NewGraph, Tag> copy_graph(NewGraph& g, Tag) {
  return graph_copier<NewGraph, Tag>(g);
}


#endif

/*

Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.

*/
